services:
  - type: web
    name: xiaobai-linebot
    runtime: python
    region: asia
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app -w 1"
    autoDeploy: true
    envVars:
      - key: LINE_CHANNEL_SECRET
        value: your_line_channel_secret
      - key: LINE_CHANNEL_ACCESS_TOKEN
        value: your_line_channel_access_token
      - key: DOUBAO_API_KEY
        value: your_doubao_api_key
