services:
  - type: web
    name: line-gptbot-freeapi
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false         # 來自 https://free.v36.cm 的免費金鑰
      - key: OPENAI_BASE_URL
        value: https://free.v36.cm/v1
        sync: false
      - key: OPENAI_MODEL_NAME
        value: gpt-3.5-turbo
        sync: false
      - key: OPENAI_SYSTEM_PROMPT
        value: "你是一位親切幽默的女僕助理，稱呼使用者為主人"
        sync: false
